# Generated by Django 5.2.5 on 2025-09-02 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tariff', models.CharField(choices=[('OSAGO', 'OSAGO'), ('KASKO', 'KASKO')], max_length=20)),
                ('driver_age', models.PositiveSmallIntegerField()),
                ('driver_experience', models.PositiveSmallIntegerField()),
                ('car_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('sport', 'Sport')], max_length=20)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coef_age', models.DecimalField(decimal_places=3, max_digits=6)),
                ('coef_exp', models.DecimalField(decimal_places=3, max_digits=6)),
                ('coef_car', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TJS', max_length=3)),
                ('ruleset_version', models.CharField(default='v1', max_length=16)),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('tariff', models.CharField(choices=[('OSAGO', 'OSAGO'), ('KASKO', 'KASKO')], max_length=20)),
                ('total_amount_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='NEW', max_length=12)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='application', to='bima.quote')),
            ],
        ),
    ]
